### ISSUE TITLE
Cannot export documents/collections with "Non-existent ancestor documents"

### ISSUE THREAD

**Issue by sonmaximum** [benyap/firestore-backfire#229]
In firestore, documents and collections can exist even if ancestors higher in the path do not (see https://cloud.google.com/firestore/docs/using-console#non-existent_ancestor_documents )

It seems that firestore-backfire does not currently export documents deeper than the non-existing ancestor - is there any way to allow it to do so?

**Comment by benyap** [comment]
Based on what it says in the documentation:

> Warning: Even though non-existent ancestor documents appear in the console, they do not appear in **queries** and snapshots. You must create the document to include it in query results.

Because `firestore-backfire` uses the Firebase SDK to **query** for documents to export, I'm fairly positive that this will **not** be possible unless the capability to find non-existent ancestor documents is exposed through the SDK.

I suppose you _could_ use the [`paths`](https://github.com/benyap/firestore-backfire#options) option to specify the paths that have non-existing ancestors - and `firestore-backfire` should be able to export them. Of course, this means you'll need to know these paths ahead of time, and this may or may not be possible/practical depending on your use case.

Sorry that this is all I can offer. I'm going going to close this for now, but feel free to continue any relevant discussion, or re-open if there is a clear path to the possibility of a working implementation!

**Comment by sonmaximum** [comment]
@benyap  Thank you for the response - what you said makes sense.  I've modified my firestore storage strategy to avoid this issue.
