### ISSUE TITLE
Document how to use dataSourceFactory.createReader() and  dataSourceFactory.createWriter() - example code is incorrect

### ISSUE THREAD

**Issue by tohagan** [benyap/firestore-backfire#418]
I've like to use your API with local files but your documentation does not explain how to do this.
Its unclear from your code what is required for `DefaultOptions & T`

Note that my paths are computed so Typescript can't see the `id` prefix in case that's used.

```ts
  const writer = await dataSourceFactory.createWriter(exportFilePath, ???)

  const reader = await dataSourceFactory.createReader(importFilePath, ???)
```

Same issue for the other pre-registered readers and writers.

**Comment by tohagan** [comment]
For code example, Typescript reports

DataSourceFactory.d.ts(120, 22): An argument for 'options' was not provided.

```ts
// Import the default factory instance
import {
  dataSourceFactory,
  importFirestoreData,
  exportFirestoreData,
} from "firestore-backfire";

const path = "s3://my-bucket/exported-data.ndjson";
const reader = await dataSourceFactory.createReader(path);  // << Typescript wants an additional option
const writer = await dataSourceFactory.createWriter(path);  // << Typescript wants an additional option

// Use the reader and writer
await importFirestoreData(connection, reader, options);
await exportFirestoreData(connection, writer, options);

```

**Comment by benyap** [comment]
Hi @tohagan,

Thanks for raising this issue. You're right in that the code example is incorrect - there is an options object that is expected as a second argument to `DataSourceFactory.createReader()` and `DataSourceFactory.createWriter()`. I'll update the documentation to correct this issue 😊

If you're using the default `dataSourceFactory` instance from firestore-backfire, the options object follows the [DataSourceOptions](https://github.com/benyap/firestore-backfire/blob/main/src/data-source/interface/options.ts#L9) interface. These options are **required** to help firestore-backfire connect to your data sources, which would be either GCS or S3.

If you've created a custom `DataSourceFactory` instance and/or registered custom data sources, you'll need to pass the options that are required for your custom data source.

The signatures of `DataSourceFactory.createReader()` and `DataSourceFactory.createWriter()` are both generic to make them extensible should you wish to register custom data sources on the existing `dataSourceFactory` instance, which is why there is a generic `T` in the type signature. By default, `DefaultOptions` should simply be [DataSourceOptions](https://github.com/benyap/firestore-backfire/blob/main/src/data-source/interface/options.ts#L9) (see [here](https://github.com/benyap/firestore-backfire/blob/main/src/data-source/factory/DataSourceFactory.ts#L87)).

Most IDEs should be able to provide you with the inferred type definition of the options object.

![image](https://github.com/benyap/firestore-backfire/assets/19235373/3dc4b4a3-76d8-4ada-abd0-ad74d927e2f0)

Hope this helps! Please let me know if you have any further questions.
